<template>
  <main class="na-page na-page--list smart-report-page">
    <AppPageHeader title-id="smart-report-title" title="智能日报" description="按日汇总异常、待办、趋势和系统健康指标；模型不可用时仍保留结构化数据。">
      <template #actions><el-button :icon="Refresh" :loading="loading" @click="load">刷新</el-button><el-button type="primary" :icon="MagicStick" :loading="generating" @click="generate">生成今日日报</el-button></template>
    </AppPageHeader>
    <AppEmptyState
      v-if="!loading && !report"
      title="今日尚未生成智能日报"
      description="生成后会汇总资产、风险、发票、协作和 AI 服务指标；模型不可用时仍保留确定性统计。"
      :highlights="['异常与待办集中汇总', '业务指标可追溯跳转', '支持应用内订阅提醒']"
    >
      <template #actions><el-button type="primary" :icon="MagicStick" :loading="generating" @click="generate">生成今日日报</el-button></template>
    </AppEmptyState>
    <section v-if="report" class="na-panel report-hero"><div><span class="eyebrow">{{ report.reportDate?.slice?.(0, 10) || '今日' }}</span><h2>{{ report.summary || '日报暂无摘要' }}</h2><small>生成方式：{{ report.generatedBy }} · {{ formatTime(report.generatedAt) }}</small></div><el-tag type="success" effect="plain">已生成</el-tag></section>
    <section v-if="report" class="metric-grid"><article v-for="item in metricCards" :key="item.key" class="na-panel metric-card" role="button" tabindex="0" @click="openMetric(item)" @keydown.enter.space.prevent="openMetric(item)"><span>{{ item.label }}</span><strong>{{ item.value }}</strong><small>{{ item.hint }}</small></article></section>
    <section v-if="report" class="na-panel detail-panel"><header class="panel-header"><div><h2>详细指标</h2><p>指标来自业务表确定性统计，模型仅负责摘要。</p></div></header><div class="detail-grid"><div v-for="item in detailMetrics" :key="item.key" class="detail-item"><span>{{ item.label }}</span><strong>{{ item.value }}</strong></div></div></section>
    <div class="report-grid">
      <section class="na-panel history-panel"><header class="panel-header"><div><h2>历史日报</h2><p>每位用户只读取自己的日报。</p></div></header><el-table v-loading="loading && !loaded" :data="reports" row-key="ID" @row-click="openReport"><el-table-column prop="reportDate" label="日期" min-width="120"><template #default="{ row }">{{ row.reportDate?.slice?.(0, 10) }}</template></el-table-column><el-table-column prop="generatedBy" label="生成方式" width="150" /><el-table-column prop="summary" label="摘要" min-width="280" show-overflow-tooltip /><template #empty><AppEmptyState compact title="暂无历史日报" description="生成第一份日报后，可在这里按日期回看业务摘要。" /></template></el-table><div class="pagination"><el-pagination v-model:current-page="page" v-model:page-size="pageSize" :total="total" layout="total, prev, pager, next" @current-change="loadHistory" /></div></section>
      <section class="na-panel subscription-panel"><header class="panel-header"><div><h2>日报订阅</h2><p>保留应用内提醒，发送时间可按用户调整。</p></div><el-switch v-model="subscription.enabled" active-text="启用" /></header><el-form label-position="top"><el-form-item label="发送时间"><el-time-picker v-model="deliveryTime" format="HH:mm" value-format="HH:mm" placeholder="选择时间" /></el-form-item><el-form-item label="渠道"><el-checkbox-group v-model="channels"><el-checkbox label="in_app">应用内</el-checkbox><el-checkbox label="email">邮件</el-checkbox></el-checkbox-group></el-form-item><el-button type="primary" :loading="saving" @click="saveSubscription">保存订阅</el-button></el-form></section>
    </div>
    <section class="na-panel deliveries-panel"><header class="panel-header"><div><h2>发送记录</h2><p>仅显示当前用户最近 30 条投递结果。</p></div></header><el-table :data="deliveries" size="small"><el-table-column prop="channel" label="渠道" width="100" /><el-table-column prop="status" label="状态" width="100" /><el-table-column prop="retryCount" label="尝试次数" width="100" /><el-table-column prop="error" label="失败原因" min-width="220" show-overflow-tooltip /><el-table-column prop="sentAt" label="发送时间" min-width="170"><template #default="{ row }">{{ formatTime(row.sentAt || row.lastAttempt) }}</template></el-table-column><template #empty><AppEmptyState compact title="暂无日报发送记录" description="启用订阅并生成日报后，投递结果会显示在这里。" /></template></el-table></section>
  </main>
</template>

<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { MagicStick, Refresh } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import AppEmptyState from '@/components/page/AppEmptyState.vue'
import AppPageHeader from '@/components/page/AppPageHeader.vue'
import { generateSmartReport, getSmartReport, getSmartReportDeliveries, getSmartReportSubscription, getSmartReports, getTodaySmartReport, saveSmartReportSubscription } from '@/plugin/smart/api/smart'

defineOptions({ name: 'SmartReport' })
const router = useRouter()
const loading = ref(false); const loaded = ref(false); const generating = ref(false); const saving = ref(false); const report = ref(null); const reports = ref([]); const deliveries = ref([]); const total = ref(0); const page = ref(1); const pageSize = ref(10); const subscription = reactive({ enabled: true, deliveryTime: '09:00', channels: 'in_app' }); const deliveryTime = ref('09:00'); const channels = ref(['in_app'])
const metricCards = computed(() => { const m = report.value?.metrics || {}; return [{ key: 'assets', label: '资产新增', value: m.assets?.created || 0, hint: `今日完成流转 ${m.assets?.todayOperationTotal || 0} 单`, route: 'assetInventory' }, { key: 'risks', label: '开放风险', value: m.risks?.open || 0, hint: `今日新增 ${m.risks?.new || 0} · 处理 ${m.risks?.resolved || 0}`, route: 'assetRiskCenter' }, { key: 'invoices', label: '待复核发票', value: m.invoices?.pendingReview || 0, hint: `低置信度 ${m.invoices?.lowConfidence || 0} · 失败 ${m.invoices?.recognitionFailed || 0}`, route: 'invoiceLedger', query: { status: 'pending_review' } }, { key: 'collaboration', label: '今日待办', value: m.collaboration?.todaySchedules || 0, hint: `未读公告 ${m.collaboration?.unreadAnnouncements || 0} 条`, route: 'workSchedule' }, { key: 'system', label: 'AI 调用', value: m.system?.aiCalls || 0, hint: `失败率 ${percentage(m.system?.aiFailureRate)}`, route: 'aiOperations' }] })
const detailMetrics = computed(() => { const m = report.value?.metrics || {}; return [{ key: 'pending', label: '待入库资产', value: m.assets?.pendingInbound || 0 }, { key: 'long-use', label: '长期在用', value: m.assets?.longTermInUse || 0 }, { key: 'maintenance', label: '维修超期', value: m.assets?.maintenanceOverdue || 0 }, { key: 'warranty-60', label: '60 天内过保', value: m.assets?.warrantyExpiring60d || 0 }, { key: 'warranty-90', label: '90 天内过保', value: m.assets?.warrantyExpiring90d || 0 }, { key: 'recognized', label: '今日识别发票', value: m.invoices?.todayRecognized || 0 }, { key: 'reviewed', label: '今日复核发票', value: m.invoices?.todayReviewed || 0 }, { key: 'confirmed', label: '今日确认发票', value: m.invoices?.todayConfirmed || 0 }, { key: 'backlog', label: '识别积压', value: m.invoices?.recognitionBacklog || 0 }, { key: 'today-amount', label: '今日确认金额', value: money(m.invoices?.confirmedTodayCents) }, { key: 'month-amount', label: '本月确认金额', value: money(m.invoices?.confirmedMonthCents) }, { key: 'ai-duration', label: 'AI 平均耗时', value: `${m.system?.aiAverageDurationMs || 0} ms` }, { key: 'ai-cost', label: 'AI 估算费用', value: `${m.system?.aiEstimatedCostMicros || 0} 微单位` }] })
function percentage(value) { return `${Number(value || 0).toFixed(1)}%` }
function money(cents) { return `¥${(Number(cents || 0) / 100).toFixed(2)}` }
function openMetric(item) { if (item.route && router.hasRoute(item.route)) router.push({ name: item.route, query: item.query }) }
function formatTime(value) { return value ? new Date(value).toLocaleString('zh-CN', { hour12: false }) : '—' }
async function loadToday() { const res = await getTodaySmartReport(); if (res.code === 0) report.value = res.data; else ElMessage.error(res.msg || '读取日报失败') }
async function loadHistory() { const res = await getSmartReports({ page: page.value, pageSize: pageSize.value }); if (res.code === 0) { reports.value = res.data?.list || []; total.value = res.data?.total || 0 } }
async function loadSubscription() { const res = await getSmartReportSubscription(); if (res.code === 0) { Object.assign(subscription, res.data || {}); deliveryTime.value = res.data?.deliveryTime || '09:00'; channels.value = (res.data?.channels || 'in_app').split(',').filter(Boolean) } }
async function loadDeliveries() { const res = await getSmartReportDeliveries(); if (res.code === 0) deliveries.value = res.data || [] }
async function load() { loading.value = true; try { await Promise.all([loadToday(), loadHistory(), loadSubscription(), loadDeliveries()]) } finally { loading.value = false; loaded.value = true } }
async function generate() { generating.value = true; try { const res = await generateSmartReport(); if (res.code === 0) { report.value = res.data; await loadHistory(); ElMessage.success(res.msg || '日报已生成') } else ElMessage.error(res.msg || '生成失败') } finally { generating.value = false } }
async function saveSubscription() { saving.value = true; try { const res = await saveSmartReportSubscription({ enabled: subscription.enabled, deliveryTime: deliveryTime.value, channels: channels.value.join(',') }); if (res.code === 0) { ElMessage.success(res.msg || '订阅已保存'); await loadDeliveries() } else ElMessage.error(res.msg || '保存失败') } finally { saving.value = false } }
async function openReport(row) { const res = await getSmartReport({ id: row.ID }); if (res.code === 0) report.value = res.data; else ElMessage.error(res.msg || '读取日报详情失败') }
onMounted(load)
</script>

<style scoped lang="scss">
.report-hero { display: flex; align-items: flex-start; justify-content: space-between; gap: 16px; margin-bottom: 14px; padding: 20px; }.eyebrow { color: var(--el-color-primary); font-size: .75rem; }.report-hero h2 { max-width: 900px; margin: 8px 0; font-size: 1.1rem; line-height: 1.6; }.report-hero small, .panel-header p, .metric-card small { color: var(--na-muted-foreground); }.metric-grid { display: grid; grid-template-columns: repeat(5, minmax(0, 1fr)); gap: 12px; margin-bottom: 14px; }.metric-card { display: flex; min-width: 0; flex-direction: column; gap: 8px; padding: 16px; cursor: pointer; transition: border-color .16s ease, box-shadow .16s ease; }.metric-card:hover, .metric-card:focus-visible { border-color: var(--el-color-primary); box-shadow: var(--na-shadow-md); outline: none; }.metric-card span { color: var(--na-muted-foreground); font-size: .78rem; }.metric-card strong { font-size: 1.45rem; font-variant-numeric: tabular-nums; }.metric-card small { min-height: 30px; font-size: .72rem; line-height: 1.4; }.detail-panel { margin-bottom: 14px; }.detail-grid { display: grid; grid-template-columns: repeat(5, minmax(0, 1fr)); border-top: 1px solid var(--na-border); border-left: 1px solid var(--na-border); }.detail-item { display: flex; min-width: 0; flex-direction: column; gap: 6px; padding: 11px 12px; border-right: 1px solid var(--na-border); border-bottom: 1px solid var(--na-border); }.detail-item span { color: var(--na-muted-foreground); font-size: .72rem; }.detail-item strong { overflow-wrap: anywhere; font-size: .9rem; font-variant-numeric: tabular-nums; }.report-grid { display: grid; grid-template-columns: minmax(0, 1fr) 320px; gap: 14px; }.na-panel { min-width: 0; padding: 16px; border: 1px solid var(--na-border); border-radius: 8px; background: var(--na-card); box-shadow: var(--na-shadow-sm); }.panel-header { display: flex; align-items: flex-start; justify-content: space-between; gap: 12px; margin-bottom: 14px; }.panel-header h2 { margin: 0; font-size: .95rem; }.panel-header p { margin: 5px 0 0; font-size: .75rem; }.subscription-panel { align-self: start; }.subscription-panel .el-time-picker { width: 100%; }.deliveries-panel { margin-top: 14px; }.pagination { display: flex; justify-content: flex-end; margin-top: 14px; }
@media (max-width: 1100px) { .metric-grid { grid-template-columns: repeat(3, minmax(0, 1fr)); }.detail-grid { grid-template-columns: repeat(3, minmax(0, 1fr)); } .report-grid { grid-template-columns: 1fr; } }
@media (max-width: 650px) { .metric-grid, .detail-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); }.report-hero { flex-direction: column; }.metric-card strong { font-size: 1.2rem; } }
</style>
